### ISSUE TITLE
Podcast generation

### ISSUE THREAD

**Issue by Cal-DCosta** [SWivid/F5-TTS#285]
I love this but a bit disappointed that the podcast generation has been taken out of the update really used that a lot, how can I get it back is there code for it I could include in the script.
thanks for your work!!!!!

**Comment by samni728** [comment]
Multiple Speech-Type Generation

**Comment by SWivid** [comment]
Hi @Cal-DCosta ~
Multiple Speech-Type Generation is just for it, and you can generate for a talk (podcast) with more guests invited now lol

**Comment by Cal-DCosta** [comment]
Ah! sorry did not realise, thanks!!!!!

**Comment by SWivid** [comment]
@Cal-DCosta Yeah, have fun~
Will close as solved, feel free to open if further questions

**Comment by timeship12** [comment]
An honest writer's review: It imitates voices very well, but when it comes to artistic reading from text with voice inflections (provided in the audio sample!), it sounds rather plain and monotonous. Hence, it's suitable ONLY to narrate documentaries and read news or essays, but NOT fiction audiobooks. After listening for a minute, you can't tell the difference between the author's voice (descriptions) and the dialogue (characters). It can't even begin to mimic human temper. Trust me, I cloned my own voice with professional dramatic reading, and it didn't follow its artistic quality at all. Great toy, but that's all it is for now. I hope someone perfects it because it has tremendous potential! ;-) THX
