### ISSUE TITLE
English Pronunciation Issues with Vowels in F5-TTS

### ISSUE THREAD

**Issue by bensonbs** [SWivid/F5-TTS#362]
#### Description
When processing English text without phoneme input, F5-TTS shows inconsistent pronunciation patterns, particularly with vowel sounds. The model appears to have difficulty distinguishing between certain vowel phonemes, leading to pronunciation confusion.

#### Specific Issues
- Confusion between different vowel sounds (AEI vowels)
- Example: "time" may be pronounced as:
  - "t em" (incorrect)
  - "t ey m" (correct pronunciation should be /taɪm/)
  
- Example 2: "I" may be pronounced as:
  - "yee" (incorrect)
  - "eye" (correct pronunciation should be /aɪ/)

**Comment by SWivid** [comment]
Yes, the current model is trained with Emilia which has many non-native English speakers in corpus.
Compare with models trained with Audio books corpus, e.g. VALL-E series, Voicebox, MS's official E2 TTS, etc, will have problems with it; and as the v1 base models are using characters rather than phonemes, it might be more hard for model to learn proper pronunciation.

WIP addressing this~
