### ISSUE TITLE
Multiple reference audios?

### ISSUE THREAD

**Issue by kunibald413** [SWivid/F5-TTS#377]
Hi, is there a way to utilize multiple reference audios to capture more characteristics?

I'm not to familiar how it works under the hood, but is some stacking or averaging possible to implement for multiple references to extract more relevant speaker characteristics?

Thank you for your time!

------

unrelated, I opened a discussion here, just a bump for visibility, maybe you have some input (LiNeS fine-tuning method)
https://github.com/SWivid/F5-TTS/discussions/295

**Comment by SWivid** [comment]
> is there a way to utilize multiple reference audios to capture more characteristics?

As far as i know, current tts models are just trying to using longer reference audio (and need to have the model trained on dataset with longer samples to support this during inference)
The problem is: how you define the way of merging multiple reference, how the stacking or averaging operation take place specifically? While using longer ref_audio, it's straightforward, but it is not easy if you come close to see how you could do the compression while keeping the original information unbroken

**Comment by kunibald413** [comment]
Ah thanks, it seems not straightforward as I understand.

xtts stacks and do a mean for all audios, this is just where i get the idea from. ofc might not be applicable here.

```py
if speaker_embeddings:
    speaker_embedding = torch.stack(speaker_embeddings)
    speaker_embedding = speaker_embedding.mean(dim=0)
```

https://github.com/coqui-ai/TTS/blob/dbf1a08a0d4e47fdad6172e433eeb34bc6b13b4e/TTS/tts/models/xtts.py#L326

if there's nothing more to it, feel free to close the issue

thank you

**Comment by SWivid** [comment]
@kunibald413 you are actually going for a right way but not an all applied way lol.
We haven't got a speaking embedding for controlling yet. The current model relies solely on reference audio (say no extra embedding extracted and serves as condition).

**Comment by SWivid** [comment]
Any suggestion is welcome~
Feel free to open an issue if further questions
