### ISSUE TITLE
AttributeError: 'BigVGAN' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hildazzz** [SWivid/F5-TTS#483]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

windows/macos

python 3.10.13

### Steps to Reproduce

1、according to option 2: Local editable (if also do training, finetuning)  
2、`f5-tts_infer-gradio`

### ✔️ Expected Behavior

using `f5-tts_infer-gradio` with `vocoder_name="bigvgan"`.

### ❌ Actual Behavior

```sh
...
  File "E:\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 208, in basic_tts
    audio_out, spectrogram_path, ref_text_out = infer(
  File "E:\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 127, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "E:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 380, in infer_process
    return infer_batch_process(
  File "E:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 465, in infer_batch_process
    generated_wave = vocoder.decode(generated_mel_spec)
  File "C:\ProgramData\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'BigVGAN' object has no attribute 'decode'
```

**Comment by SWivid** [comment]
ref to #463

**Comment by hildazzz** [comment]
Some problems with parameter passing, solved!  And thanks!

**Comment by wyvernbai** [comment]
> check and fix
> 
> https://github.com/SWivid/F5-TTS/blob/84db0029ce822f75593ba66997cc687327658e71/src/f5_tts/infer/utils_infer.py#L458-L462
> 
> 
> I haven't used the gradio to inference and you can use infer_cli

same issue on the `trainer.py` at line 331 and 343 during using bigvgan for model training.

**Comment by saiful9379** [comment]
> check and fix
I have got same issue after 17 epochs. Could you please suggest to me why this issue is raised?
`Epoch 17/1000: 100%|█████████████████████████████████████████████████████| 2939/2939 [43:43<00:00,  1.12step/s, loss=0.729, step=49963]
Epoch 18/1000:   1%|▋                                                      | 36/2939 [00:37<51:01,  1.05s/step, loss=0.711, step=50000]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/raid/TTS_RND/F5-TTS/src/f5_tts/train/train.py", line 226, in <module>
[rank0]:     main()
[rank0]:   File "/raid/TTS_RND/F5-TTS/src/f5_tts/train/train.py", line 219, in main
[rank0]:     trainer.train(
[rank0]:   File "/raid/TTS_RND/F5-TTS/src/f5_tts/model/trainer.py", line 462, in train
[rank0]:     vocoder.decode(batch["mel"][0].unsqueeze(0)),
[rank0]:   File "/home/u001/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'BigVGAN' object has no attribute 'decode'
`
