### ISSUE TITLE
duration prediction

### ISSUE THREAD

**Issue by eschmidbauer** [SWivid/F5-TTS#8]
Thank you for sharing this project and models. Testing inference and it is _very_ impressive. 
One thing i have noticed is how sensitive the `fix_duration` value is-- if it is off by 1s , the utterance may miss a word.
Is there a way to predict duration so it is accurate on each utterance? 
Thanks again for sharing this work!

**Comment by SWivid** [comment]
We currently estimate the duration linearly (if the prompt is not too short or of very high speed, it will work), or we just set a fixed duration.
A separately trained duration predictor model could be leveraged to provide the duration info, though I thought to control precisely the duration of each utterance is more of the way Voicebox does.
But for sure, we could have a utterance-level duration predictor and just pass in the add-up duration to TTS model.

**Comment by ABC0408** [comment]
Hello, the speech generated by the model is very good. The generated speech is here, with the reference speech at the beginning. https://drive.google.com/file/d/1u-RcUFTnCaYQ59zINZQdSCxV-n_tMcKy/view?usp=sharing
1. Was the word repetition caused by the longer predicted duration? 
2. Is there any good method to remove the noise at 16.3 seconds?


text  : [" Today I lead MIT's Computer Science and AI Lab, the largest research unit at MIT.Hello everyone, welcome to our live broadcast! I’m your host, Cash. Today, we’re excited to introduce a super popular lipstick, Flame Rose Red! First, let’s take a look at the packaging design of this lipstick. Isn’t it exquisite?"]
pinyin: [[' ', 'T', 'o', 'd', 'a', 'y', ' ', 'I', ' ', 'l', 'e', 'a', 'd', ' ', 'M', 'I', 'T', "'", 's', ' ', 'C', 'o', 'm', 'p', 'u', 't', 'e', 'r', ' ', 'S', 'c', 'i', 'e', 'n', 'c', 'e', ' ', 'a', 'n', 'd', ' ', 'A', 'I', ' ', 'L', 'a', 'b', ',', ' ', 't', 'h', 'e', ' ', 'l', 'a', 'r', 'g', 'e', 's', 't', ' ', 'r', 'e', 's', 'e', 'a', 'r', 'c', 'h', ' ', 'u', 'n', 'i', 't', ' ', 'a', 't', ' ', 'M', 'I', 'T', '.', ' ', 'H', 'e', 'l', 'l', 'o', ' ', 'e', 'v', 'e', 'r', 'y', 'o', 'n', 'e', ',', ' ', 'w', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 'o', 'u', 'r', ' ', 'l', 'i', 'v', 'e', ' ', 'b', 'r', 'o', 'a', 'd', 'c', 'a', 's', 't', '!', ' ', 'I', "'", 'm', ' ', 'y', 'o', 'u', 'r', ' ', 'h', 'o', 's', 't', ',', ' ', 'C', 'a', 's', 'h', '.', ' ', 'T', 'o', 'd', 'a', 'y', ',', ' ', 'w', 'e', "'", 'r', 'e', ' ', 'e', 'x', 'c', 'i', 't', 'e', 'd', ' ', 't', 'o', ' ', 'i', 'n', 't', 'r', 'o', 'd', 'u', 'c', 'e', ' ', 'a', ' ', 's', 'u', 'p', 'e', 'r', ' ', 'p', 'o', 'p', 'u', 'l', 'a', 'r', ' ', 'l', 'i', 'p', 's', 't', 'i', 'c', 'k', ',', ' ', 'F', 'l', 'a', 'm', 'e', ' ', 'R', 'o', 's', 'e', ' ', 'R', 'e', 'd', '!', ' ', 'F', 'i', 'r', 's', 't', ',', ' ', 'l', 'e', 't', "'", 's', ' ', 't', 'a', 'k', 'e', ' ', 'a', ' ', 'l', 'o', 'o', 'k', ' ', 'a', 't', ' ', 't', 'h', 'e', ' ', 'p', 'a', 'c', 'k', 'a', 'g', 'i', 'n', 'g', ' ', 'd', 'e', 's', 'i', 'g', 'n', ' ', 'o', 'f', ' ', 't', 'h', 'i', 's', ' ', 'l', 'i', 'p', 's', 't', 'i', 'c', 'k', '.', ' ', 'I', 's', 'n', "'", 't', ' ', 'i', 't', ' ', 'e', 'x', 'q', 'u', 'i', 's', 'i', 't', 'e', '?']]
2393 82 230 629
Generated mel: torch.Size([1, 2393, 100])
Generated wav: torch.Size([1, 612352]), ./speakers/TED.MP3

**Comment by SWivid** [comment]
1. Yes, the base model is trained on Emilia which only contains up-to-30s speech, and a longer speech to generate is less robust as the model hasn't seen that much long sequence data.
    AND, give some notes for model, e.g. add a comma (or a blank) to explicitly tell the pause for a long sentence;
    OR, maybe simply with re-ranking

2. To solve the noise is similar, lower case to 'flame rose red' might also help
