### ISSUE TITLE
generation issues

### ISSUE THREAD

**Issue by AznamirWoW** [SWivid/F5-TTS#89]
1) using inference-cli with a large text splits the generation into multiple batches, but at the start of the next batch a random sounds gets added.

2) generation reads hyphenated compound word like  "half-assed", "power-mad", "look-alike" as separate words, breaking the flow.

**Comment by SWivid** [comment]
Might provide us with used samples and texts to figure out ~

**Comment by jpgallegoar** [comment]
1) I noticed random sounds are usually a sign of a bad reference audio, which has harsh or low quality sounds, or audios which are trimmed / cropped incorrectly, meaning that the audio starts or ends in a sound instead of a silence. This can also happen if the reference text or the input text is not properly punctuated (it's best practice to end the reference text with a "." and to start the input text with a " ", from my testing).

2) This is an issue with how the model was trained, and would require a re-train / fine-tune to fix.

**Comment by AznamirWoW** [comment]
> Might provide us with used samples and texts to figure out ~

[test.zip](https://github.com/user-attachments/files/17375687/test.zip)
reference text contains a trailing space.

1) batch splits with issues happen with

"an" + "Then again,"
"an" + "It was a blind spot"
"an" + "However,"
"e" + "Remember,"
"adie" + "This is why"

2) hyphenated words in the example with issues are "nose-rub", "power-mad"

**Comment by AznamirWoW** [comment]
by the way, E2-TTS model speaks "nose-rub" correctly, but stumbles on "power-mad", same issues with the batch split, but  different sound

**Comment by AznamirWoW** [comment]
[ref_david.zip](https://github.com/user-attachments/files/17375951/ref_david.zip)

Using another reference voice, but same reference and generation texts I've noticed massive issues - in addition to the separation there are distortions with the reproduction o the text

"subjected to a plaintive ????????????? the parallel at all"

**Comment by AznamirWoW** [comment]
[ref_andy.zip](https://github.com/user-attachments/files/17376191/ref_andy.zip)
Another test with a different reference, same inputs

"Magic just appreciates the attention.... bzzzzzzzzz"
"container of food for ?????????????????? -rub while not seeing the parallel at all..... bzzzzzzzzzz"
"wizard has certain ???????????? they keep locked away" "also.... bzzzzzz"
"heroes arise ???? to battle the forces"

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
