### ISSUE TITLE
Multiple Speech-Type Generation   API  support 

### ISSUE THREAD

**Issue by fastfading** [SWivid/F5-TTS#91]
I wish
1. Multiple reference audio could be load at beginning. 
2. api could call 1 style at 1 api call. 
3. make this api call almost real time ,  generation delay < 1s  for 1 short sentence, I thought the train step may take most time. the generating step would take less time.

**Comment by SWivid** [comment]
@jpgallegoar might help~

**Comment by jpgallegoar** [comment]
The problem with 1) is that it would make it much more hardware intensive since you have to store all reference audios in VRAM instead of just one reference audio (I might be wrong on this). One optimization I did think of is generating all of the audios with the same speech type consecutively to save time, and then stitching them together accordingly. Either way, this is something I'd like to look into but unfortunately I don't have time to do it today.

2) Is possible, but I don't see the benefit of adding Multi-speech type to api in this manner since it's the same as generating the audios the regular way. It could be interesting to add it to the api, but by doing everything in one single api call instead of 1 style per api call.

3) I'm not sure how we could improve upon this step. 

All ideas and help are appreciated.

**Comment by fastfading** [comment]
@jpgallegoar, consider this scenario:

You are playing a galgame, and most galgames nowadays do not have voice acting. There are multiple characters, and each character has a specific voice type. Even a single character can have multiple emotional expressions.

Here’s what I would like to achieve:

Pre-load all audio: All audio should be loaded at the beginning, and the relevant parameters for each should be pre-calculated.
API calls: During gameplay, the galgame should call the API based on the character and their current emotion.
Fast audio generation: Audio should be generated in a very short time, ideally within 2 seconds per sentence. This is why step 1 is important—step 3’s time cost should only involve audio generation, not loading or other processes.

--------
@jpgallegoar，请考虑以下场景：

你正在玩一款galgame，现在大多数galgame都没有语音配音。这类游戏中有多个角色，每个角色都有一个特定的音色。即使是同一个角色，也会有多种情感表达。

我希望实现以下功能：

预加载所有音频：在游戏开始时，所有音频都应该被加载，并且相关的参数都应该预先计算好。
调用API：在游戏过程中，根据角色和当前的情感状态，游戏应调用相应的API。
快速生成音频：音频应在非常短的时间内生成，理想情况下每句话的生成时间应在2秒以内。这就是为什么第1步很重要——第3步的时间开销应该仅限于音频生成，而不包括加载或其他过程。

**Comment by jpgallegoar** [comment]
I will look into this once I finish with the spanish finetune I'm doing. Thanks for the idea!

**Comment by fastfading** [comment]
@jpgallegoar  多谢， 下面这些link 会帮助到你

galgame 翻译器和tts外挂  https://github.com/HIllya51/LunaTranslator
情绪的简单设计方案           https://github.com/2DIPW/gpt_sovits_infer_with_emotion
语音素材   https://www.bilibili.com/read/cv23965717/
