### ISSUE TITLE
Why convnext instead of transformer?

### ISSUE THREAD

**Issue by sphmel** [SWivid/F5-TTS#96]
it seems transformer architectural difference is small(alibi -> rotary, concat time emb -> AdaLN-Zero, no u-net connection)

why not transformer instead of ConvNeXt? did you guys. test it, and convnext was better?

**Comment by SWivid** [comment]
welcome to make this ablation

we have tested with mmdit and results in failures, which is a double-stream transformer
maybe something like fluxmusic modification suits more for tts task

thought a minor difference in architecture will change a lot, otherwise it's just as simple as you could imagine to reproduce e2

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
